// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeQXuUDHAWRzMDltYg4FhL2saV3n1ejts',
    appId: '1:959594532472:web:9fea352c8820fef690a78d',
    messagingSenderId: '959594532472',
    projectId: 'la8iny-7de07',
    authDomain: 'la8iny-7de07.firebaseapp.com',
    storageBucket: 'la8iny-7de07.firebasestorage.app',
    measurementId: 'G-ST5V5GMH1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAIFgntKhv3f0uHAK9_3gAFkvptKIrdU',
    appId: '1:959594532472:android:6cec7d4eaa10a17190a78d',
    messagingSenderId: '959594532472',
    projectId: 'la8iny-7de07',
    storageBucket: 'la8iny-7de07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1XQBsTgfZ5Y_32ZWlAyzCp1BOivGoEE',
    appId: '1:959594532472:ios:568b0d6036b0b5b490a78d',
    messagingSenderId: '959594532472',
    projectId: 'la8iny-7de07',
    storageBucket: 'la8iny-7de07.firebasestorage.app',
    iosBundleId: 'com.example.blocDepth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1XQBsTgfZ5Y_32ZWlAyzCp1BOivGoEE',
    appId: '1:959594532472:ios:568b0d6036b0b5b490a78d',
    messagingSenderId: '959594532472',
    projectId: 'la8iny-7de07',
    storageBucket: 'la8iny-7de07.firebasestorage.app',
    iosBundleId: 'com.example.blocDepth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeQXuUDHAWRzMDltYg4FhL2saV3n1ejts',
    appId: '1:959594532472:web:084adbbe8c9c6f6f90a78d',
    messagingSenderId: '959594532472',
    projectId: 'la8iny-7de07',
    authDomain: 'la8iny-7de07.firebaseapp.com',
    storageBucket: 'la8iny-7de07.firebasestorage.app',
    measurementId: 'G-T685YKK80V',
  );
}
